/* eslint-disable @typescript-eslint/no-require-imports */
import type { Metadata } from "next";
import "./globals.css";
import { MSWProvider } from "@/components/MSWComponent";
import AuthSession from "@/components/AuthSession";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

if (
  process.env.NEXT_RUNTIME === "nodejs" &&
  process.env.NODE_ENV !== "production"
) {
  const { server } = require("@/mocks/http"); // 개발모드이고 node.js 환경일때 (서버 컴포넌트일때)
  server?.listen();
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MSWProvider>
          <AuthSession>{children}</AuthSession>
        </MSWProvider>
      </body>
    </html>
  );
}
