/* eslint-disable @typescript-eslint/no-require-imports */
import type { Metadata } from "next";
import "./globals.css";
import { MSWProvider } from "@/components/MSWComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

if (
  process.env.NEXT_RUNTIME === "nodejs" &&
  process.env.NODE_ENV !== "production"
) {
  const { server } = require("@/mocks/http");
  server?.listen();
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MSWProvider>{children}</MSWProvider>
      </body>
    </html>
  );
}
